[package]
name = "gete-say-hello"
version = "0.3.0"
edition = "2024"
description = "This is say hello libary"
license = "Apache-2.0"

[features]
hello = []
bye = []
all = ["hello", "bye"]
defult = ["hello"]

[dependencies]
